### ISSUE TITLE
error state

### ISSUE THREAD

**Issue by ghost** [cs361-W16/Group16-2#11]
we need a new image for our "error states". The error states will only affect 2 areas:

1- Discard: If a user tries to discard an inelligable card, the trash can should have an x over the top or display an "invalid move notification

2- Deal: if the deck is empty, the user should be notified in a simliar fashion as area 1. 

These will be assigned to Neil

**Comment by alecno20** [comment]
These will be assigned to Neil - Neil.... hahaahahahaha
